name: 🪙 AliExpress Coin Bot

on:
  schedule:
    - cron: '0 7 * * *'  # 7:00 AM UTC (4:00 AM BRT)
  workflow_dispatch:      # Permite execução manual

jobs:
  collect-coins:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: ⎔ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: 📦 Install ALL dependencies
      run: |
        npm install

    - name: 🚀 Run AliExpress Bot
      env:
        ALIEXPRESS_EMAIL: ${{ secrets.ALIEXPRESS_EMAIL }}
        ALIEXPRESS_PASSWORD: ${{ secrets.ALIEXPRESS_PASSWORD }}
      run: node ./scripts/bot-ali-gh-actions.js

    - name: 📋 Show execution logs
      if: always()
      run: |
        echo "✅ Bot execution completed!"
        echo "📅 Next run: tomorrow at 7:00 AM UTC"
